export declare const segmentsL: number
export declare const getBezierPosition: Callback
export declare const getPointDistance: Callback
export declare const getAdjustedT: Callback
export declare const sortPoints: Callback
export declare const drawRope: Callback
export declare const createRope: Callback
export declare const createOrb: Callback
export declare const renderRope: Callback